# Generated by Django 5.1.1 on 2024-09-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0002_polygon_polygon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polygon',
            new_name='Polygon_model',
        ),
    ]
