# Generated by Django 5.1.1 on 2024-09-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0003_rename_polygon_polygon_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polygon_model',
            new_name='PolygonModel',
        ),
    ]
