# Generated by Django 4.2.16 on 2024-09-25 13:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Неизвестный полигон', max_length=120)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('coordinate_line', models.CharField(max_length=200, null=True)),
                ('antimeridian', models.BooleanField(null=True)),
            ],
        ),
    ]
