# Generated by Django 4.2.16 on 2024-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='coordinates',
            field=models.CharField(default='(0,1)', max_length=120),
            preserve_default=False,
        ),
    ]
